import yfinance as yf

def check_stock_symbols(symbols):
    for symbol in symbols:
        try:
            stock = yf.Ticker(symbol)
            # Try fetching some historical data (like the last 5 days)
            data = stock.history(period="1y")
            if data.empty:
                print(f"Warning: {symbol} is listed, but no historical data found.")
        
        except Exception as e:
            print(f"Error: {symbol} may not be listed or there was an issue fetching data. {e}")
    print('checking completed')

# List of stock symbols to check
symbols = [
    'AARTIIND.NS',
    'ABB.NS',
    'ACC.NS',
    'AMBUJACEM.NS',
    'APLAPOLLO.NS',
    'APOLLOTYRE.NS',
    'ASIANPAINT.NS',
    'ASKOKLEY.NS',
    'ASTRAL.NS',
    'AUROPHARMA.NS',
    'AXISBANK.NS',
    'BAJAJ-AUTO.NS',
    'BALKRISIND.NS',
    'BANKBARODA.NS',
    'BATAINDIA.NS',
    'BEL.NS',
    'BEML.NS',
    'BERGEPAINT.NS',
    'BHARATFORG.NS',
    'BHARTIARTL.NS',
    'BHEL.NS',
    'BRITANNIA.NS',
    'CANBK.NS',
    'CIPLA.NS',
    'COALINDIA.NS',
    'CONCOR.NS',
    'CUMMINSIND.NS',
    'DABUR.NS',
    'DALBHARAT.NS',
    'DEEPAKFERT.NS',
    'DEVYANI.NS',
    'EICHERMOT.NS',
    'FSL.NS',
    'GAIL.NS',
    'GNFC.NS',
    'GODFRYPHLP.NS',
    'GODREJCP.NS',
    'GRANULES.NS',
    'GRASIM.NS',
    'GRSE.NS',
    'HAL.NS',
    'HAVELS.NS',
    'HCLTECH.NS',
    'HDFCBANK.NS',
    'HEROMOTOCO.NS',
    'HINDALCO.NS',
    'HINDCOPPER.NS',
    'HINDUNILVR.NS',
    'HINDZINC.NS',
    'ICICIBANK.NS',
    'IEX.NS',
    'INDHOTEL.NS',
    'INDIAMART.NS',
    'INDUSINDBK.NS',
    'INDUSTOWER.NS',
    'INFY.NS',
    'INTELLECT.NS',
    'ITC.NS',
    'JINDALSTEL.NS',
    'JIOFIN.NS',
    'JSWSTEEL.NS',
    'KOTAKBANK.NS',
    'KPITTECH.NS',
    'LT.NS',
    'LTIM.NS',
    'M&M.NS',
    'MARICO.NS',
    'MARUTI.NS',
    'MOTHERSON.NS',
    'MRPL.NS',
    'NATIONALUM.NS',
    'NESTLEIND.NS',
    'NMDC.NS',
    'NTPC.NS',
    'NYKAA.NS',
    'ONGC.NS',
    'PIDLITIND.NS',
    'POLYCAB.NS',
    'POLYPLEX.NS',
    'POWERGRID.NS',
    'RAYMOND.NS',
    'RELIANCE.NS',
    'SAIL.NS',
    'SBIN.NS',
    'SIRCA.NS',
    'SRF.NS',
    'STARCEMENT.NS',
    'SUNPHARMA.NS',
    'TATACHEM.NS',
    'TATACONSUM.NS',
    'TATAELXI.NS',
    'TATAMOTORS.NS',
    'TATAPOWER.NS',
    'TATASTEEL.NS',
    'TATATECH.NS',
    'TCS.NS',
    'TECHM.NS',
    'TITAN.NS',
    'TRITURBINE.NS',
    'TTKPRESTIG.NS',
    'TVSMOTOR.NS',
    'UBL.NS',
    'UPL.NS',
    'VEDL.NS',
    'VOLTAS.NS',
    'WIPRO.NS',
    'ZENTEC.NS',
    'ZOMATO.NS',
]

# Check if each stock symbol is listed
check_stock_symbols(symbols)
