import yfinance as yf

def check_stock_symbols(symbols):
    for symbol in symbols:
        try:
            stock = yf.Ticker(symbol)
            # Try fetching some historical data (like the last 5 days)
            data = stock.history(period="1y")
            if data.empty:
                print(f"Warning: {symbol} is listed, but no historical data found.")
        
        except Exception as e:
            print(f"Error: {symbol} may not be listed or there was an issue fetching data. {e}")
    print('checking completed')

# List of stock symbols to check

symbols = [
    '^CNXAUTO',
    '^CNXFMCG',
    '^CNXIT',
    '^CNXMETAL',
    '^CNXPHARMA',
    '^NSEBANK',
    '^NSEI',
    '^BSESN',
    'ABB.NS',
    'ACC.NS',
    'APLAPOLLO.NS',
    'APOLLOTYRE.NS',
    'ASIANPAINT.NS',
    'AXISBANK.NS',
    'BAJAJ-AUTO.NS',
    'BANKBARODA.NS',
    'BATAINDIA.NS',
    'BEL.NS',
    'BEML.NS',
    'BEPL.NS',
    'BERGEPAINT.NS',
    'BHARTIARTL.NS',
    'BHEL.NS',
    'BPCL.NS',
    'BRITANNIA.NS',
    'BSOFT.NS',
    'CANBK.NS',
    'CASTROLIND.NS',
    'CDSL.NS',
    'CHAMBLFERT.NS',
    'CIPLA.NS',
    'COALINDIA.NS',
    'CONCOR.NS',
    'CROMPTON.NS',
    'CUMMINSIND.NS',
    'DABUR.NS',
    'DALBHARAT.NS',
    'DRREDDY.NS',
    'EICHERMOT.NS',
    'ESCORTS.NS',
    'FSL.NS',
    'GAIL.NS',
    'GESHIP.NS',
    'GODFRYPHLP.NS',
    'GRSE.NS',
    'HAL.NS',
    'HAVELLS.NS',
    'HCLTECH.NS',
    'HDFCBANK.NS',
    'HEROMOTOCO.NS',
    'HINDALCO.NS',
    'HINDCOPPER.NS',
    'HINDUNILVR.NS',
    'HINDZINC.NS',
    'ICICIBANK.NS',
    'IEX.NS',
    'INDHOTEL.NS',
    'INDIAMART.NS',
    'INDUSINDBK.NS',
    'INFY.NS',
    'INTELLECT.NS',
    'IOC.NS',
    'IRCTC.NS',
    'ITC.NS',
    'JKTYRE.NS',
    'JSWSTEEL.NS',
    'JYOTHYLAB.NS',
    'KNRCON.NS',
    'KOTAKBANK.NS',
    'KPITTECH.NS',
    'LICI.NS',
    'LT.NS',
    'LTIM.NS',
    'M&M.NS',
    'MARICO.NS',
    'MARUTI.NS',
    'MRPL.NS',
    'NATCOPHARM.NS',
    'NATIONALUM.NS',
    'NESTLEIND.NS',
    'NMDC.NS',
    'NTPC.NS',
    'ONGC.NS',
    'PIDILITIND.NS',
    'POLYCAB.NS',
    'POWERGRID.NS',
    'RAYMOND.NS',
    'RELIANCE.NS',
    'RENUKA.NS',
    'RITES.NS',
    'RVNL.NS',
    'SAIL.NS',
    'SBIN.NS',
    'SIRCA.NS',
    'SRF.NS',
    'SUNPHARMA.NS',
    'TANLA.NS',
    'TATACHEM.NS',
    'TATAELXSI.NS',
    'TATAMOTORS.NS',
    'TATAPOWER.NS',
    'TATASTEEL.NS',
    'TATATECH.NS',
    'TCS.NS',
    'TECHM.NS',
    'TITAN.NS',
    'TRITURBINE.NS',
    'UBL.NS',
    'USHAMART.NS',
    'VBL.NS',
    'VEDL.NS',
    'VOLTAS.NS',
    'VSTIND.NS',
    'WIPRO.NS',
    'ZENTEC.NS',
    'ZOMATO.NS',
    ]


# Check if each stock symbol is listed
check_stock_symbols(symbols)
